import { useCallback, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useMenu } from "../Context/MenuContext";

import menu from "../data/menu";
import styles from "../styles/index.module.scss";

import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/effect-coverflow";
import { EffectCoverflow } from "swiper/modules";

const AdminPage = () => {
  const { addToMenu, removeFromMenu, menuItems } = useMenu();
  const [currentPage, setCurrentPage] = useState(1);
  const [activeIndex, setActiveIndex] = useState(0);
  const imagesToShow = menu.items;
  const blurDataURL = menu.image;

  const handleAddOrRemoveFromMenu = useCallback(
    (index) => {
      const currentItem = imagesToShow[index];
      const itemInMenu = menuItems.find(
        (menuItem) =>
          menuItem.id === currentItem.id && menuItem.origin === "/AdminPage"
      );

      if (itemInMenu) {
        removeFromMenu({
          id: currentItem.id,
          origin: "/AdminPage",
        });
      } else {
        addToMenu({
          id: currentItem.id,
          image: currentItem.imagen,
          price: currentItem.precio,
          name: currentItem.nombre,
          descrip: currentItem.descripcion,
          origin: "/AdminPage",
        });
      }
    },
    [addToMenu, removeFromMenu, menuItems, imagesToShow]
  );

  return (
    <>
      <Head>
        <title>AdminPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.Main}>
        <header>
          <Swiper
            effect={"coverflow"}
            grabCursor={true}
            centeredSlides={true}
            slidesPerView={"auto"}
            coverflowEffect={{
              rotate: 50,
              stretch: 0,
              depth: 100,
              modifier: 1,
              slideShadows: true,
            }}
            onSlideChange={(swiper) => setActiveIndex(swiper.activeIndex)} // Actualizar el índice activo
            modules={[EffectCoverflow]}
          >
            {imagesToShow.map((item, index) => (
              <SwiperSlide key={index}>
                <section>
                  <Image
                    src={item.imagen}
                    alt={`Imagen ${index + 1}`}
                    width={200}
                    height={200}
                    lazy="loading"
                    // placeholder="blur"
                    blurDataURL={blurDataURL}
                  />
                  <h3>{item.nombre}</h3>
                  <h3>{item.precio} $</h3>
                  <p>{item.descripcion}</p>
                </section>
              </SwiperSlide>
            ))}
          </Swiper>
        </header>
      </main>
      <div className={styles.MenuButton}>
        <button onClick={() => handleAddOrRemoveFromMenu(activeIndex)}>
          {menuItems.some(
            (menuItem) =>
              menuItem.id === imagesToShow[activeIndex].id &&
              menuItem.origin === "/AdminPage"
          )
            ? "Remover del Menu"
            : "Agregar al Menu"}
        </button>
      </div>
      <Link href={"/"}>Menu</Link>
    </>
  );
};

export default AdminPage;
