import { useMenu } from "../Context/MenuContext";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/index.module.scss";

import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/effect-creative";
import { EffectCreative } from "swiper/modules";

const Menu = () => {
  const { menuItems, removeFromMenu, menuCount } = useMenu();

  return (
    <>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.Menu}>
        <h1>Menu</h1>
        <header>
          <Swiper
            grabCursor={true}
            effect={"creative"}
            creativeEffect={{
              prev: {
                shadow: true,
                translate: [0, 0, -400],
              },
              next: {
                translate: ["100%", 0, 0],
              },
            }}
            modules={[EffectCreative]}
          >
            {menuItems.map((item, index) => (
              <SwiperSlide key={index}>
                <section>
                  <Image
                    src={item.image}
                    width={300}
                    height={300}
                    alt={`Producto ${index + 1}`}
                    priority={false}
                  />
                  <p>{item.name}</p>
                  <p>
                    {item.price} $
                  </p>
                </section>
              </SwiperSlide>
            ))}
          </Swiper>
        </header>
      </main>
      <Link href={"/AdminPage"}>AdminPAge</Link>
    </>
  );
};

export default Menu;
