import React, { useState } from 'react';
import { useMenu } from "../context/MenuContext";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";
import { motion, AnimatePresence } from 'framer-motion';

import styles from "../styles/index.module.scss";

const Kitchen = () => {
  const { kitchenOrders, removeFromKitchen } = useMenu();
  const [selectedSection, setSelectedSection] = useState('');

  const sections = Array.from({ length: 14 }, (_, i) => (i + 1).toString());

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
  };

  return (
    <>
      <Head>
        <title>Kitchen Orders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>Kitchen Orders</h1>
      <main className={styles.kitchenContainer}>
        <section>
          {sections.map((section) => (
            <motion.button
              key={section}
              onClick={() => setSelectedSection(section)}
              whileHover={{ scale: 1.1 }}
              whileTap={{ scale: 0.9 }}
            >
              Mesa {section}
            </motion.button>
          ))}
        </section>
        <AnimatePresence>
          {selectedSection && (
            <motion.div
              key={selectedSection}
              variants={containerVariants}
              initial="hidden"
              animate="visible"
              exit="hidden"
            >
              {kitchenOrders[selectedSection] && kitchenOrders[selectedSection].length > 0 ? (
                kitchenOrders[selectedSection].map((order, index) => (
                  <motion.div key={index} variants={itemVariants} className={styles.itemsContainer}>
                    <h2>Order Number: {order.orderNumber}</h2>
                    {order.items.map((item, itemIndex) => (
                      <div key={itemIndex}>
                        <Image
                          src={item.image}
                          width={100}
                          height={100}
                          alt={`Order item ${index + 1}`}
                          priority={false}
                        />
                        <p>{item.name}</p>
                        <p>{item.price} $</p>
                        <p>Quantity: {item.quantity}</p>
                      </div>
                    ))}
                    <button onClick={() => removeFromKitchen(order.orderNumber)}>Remove Order</button>
                  </motion.div>
                ))
              ) : (
                <p>No hay ítems en el momento.</p>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </main>
      <Link href={"/"}>Menu</Link>
    </>
  );
};

export default Kitchen;