import { useState } from 'react';
import { useMenu } from "../context/MenuContext";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

const Kitchen = () => {
  const { kitchenOrders } = useMenu();
  const [selectedSection, setSelectedSection] = useState('');

  const sections = Object.keys(kitchenOrders);

  return (
    <>
      <Head>
        <title>Kitchen Orders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>Kitchen Orders</h1>
        <div>
          {sections.map((section) => (
            <button key={section} onClick={() => setSelectedSection(section)}>
              Section {section}
            </button>
          ))}
        </div>
        {selectedSection && kitchenOrders[selectedSection] && (
          <div>
            {Array.isArray(kitchenOrders[selectedSection]) && kitchenOrders[selectedSection].length === 0 ? (
              <p>No orders in this section.</p>
            ) : (
              kitchenOrders[selectedSection].map((order, index) => (
                <div key={index}>
                  <h2>Order Number: {order.orderNumber}</h2>
                  {order.items.map((item, itemIndex) => (
                    <div key={itemIndex}>
                      <Image
                        src={item.image}
                        width={100}
                        height={100}
                        alt={`Order item ${index + 1}`}
                        priority={false}
                      />
                      <p>{item.name}</p>
                      <p>{item.price} $</p>
                      <p>Quantity: {item.quantity}</p>
                    </div>
                  ))}
                </div>
              ))
            )}
            {!Array.isArray(kitchenOrders[selectedSection]) && <p>No orders in this section.</p>}
          </div>
        )}
      </main>
      <Link href={"/"}>Menu</Link>
    </>
  );
};

export default Kitchen;