import { useState } from 'react';
import { useMenu } from "../context/MenuContext";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/index.module.scss";

const SendOrder = () => {
  const { orderItems, addToOrder, removeFromOrder, addToKitchen } = useMenu();
  const [orderNumber, setOrderNumber] = useState('');
  const [orderSent, setOrderSent] = useState(false);

  const handleSendOrder = () => {
    const orderNum = parseInt(orderNumber, 10);
    if (!orderNumber || isNaN(orderNum) || orderNum < 1 || orderNum > 14) {
      alert('Please enter a valid order number between 1 and 14');
      return;
    }
    addToKitchen(orderNumber);
    setOrderSent(true);
    setOrderNumber('');
  };

  return (
    <>
      <Head>
        <title>Send Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>Your Order</h1>
        {orderItems.length === 0 ? (
          <p>No items in the order.</p>
        ) : (
          orderItems.map((item, index) => (
            <div key={index}>
              <Image
                src={item.image}
                width={100}
                height={100}
                alt={`Order item ${index + 1}`}
                priority={false}
              />
              <p>{item.name}</p>
              <p>{item.price} $</p>
              <div className={styles.orderContainer}>
                <button className={styles.sendOrder} onClick={() => addToOrder(item)}>+</button>
                <p>{item.quantity}</p>
                <button className={styles.sendOrder} onClick={() => removeFromOrder(item)}>-</button>
              </div>
            </div>
          ))
        )}
        <div>
          <input 
            type="number"
            value={orderNumber}
            onChange={(e) => setOrderNumber(e.target.value)}
            placeholder="Enter order number"
            min="1"
            max="14"
          />
          <button onClick={handleSendOrder}>Enviar Orden</button>
        </div>
        {orderSent && <p>Orden enviada</p>}
      </main>
      <Link href={"/Kitchen"}>Kitchen</Link>
    </>
  );
};

export default SendOrder;
