import { useMenu } from "../context/MenuContext";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";


const SendOrder = () => {
  const { orderItems, addToOrder, removeFromOrder } = useMenu();

  return (
    <>
      <Head>
        <title>Send Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>Your Order</h1>
        {orderItems.length === 0 ? (
          <p>No items in the order.</p>
        ) : (
          orderItems.map((item, index) => (
            <div key={index}>
              <Image
                src={item.image}
                width={100}
                height={100}
                alt={`Order item ${index + 1}`}
                priority={false}
              />
              <p>{item.name}</p>
              <p>{item.price} $</p>
              <p>Quantity: {item.quantity}</p>
              <button onClick={() => addToOrder(item)}>+</button>
              <button onClick={() => removeFromOrder(item)}>-</button>
            </div>
          ))
        )}
      </main>
      <Link href={"/"}>Back to Menu</Link>
    </>
  );
};

export default SendOrder;



  