import { useState } from 'react';
import { useMenu } from "../context/MenuContext";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/index.module.scss";

import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/effect-creative";
import { EffectCreative } from "swiper/modules";

const Menu = () => {
  const { menuItems, addToOrder, removeFromOrder, orderItems } = useMenu();
  const [activeIndex, setActiveIndex] = useState(0);

  const getCurrentItemQuantity = () => {
    if (menuItems.length === 0 || activeIndex >= menuItems.length) {
      return 0;
    }
    const currentItem = menuItems[activeIndex];
    const orderItem = orderItems.find(item => item.id === currentItem.id);
    return orderItem ? orderItem.quantity : 0;
  };

  return (
    <>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.Menu}>
        <h1>Menu</h1>
        {menuItems.length > 0 ? (
          <>
            <header>
              <Swiper
                grabCursor={true}
                effect={"creative"}
                creativeEffect={{
                  prev: {
                    shadow: true,
                    translate: [0, 0, -400],
                  },
                  next: {
                    translate: ["100%", 0, 0],
                  },
                }}
                modules={[EffectCreative]}
                onSlideChange={(swiper) => setActiveIndex(swiper.activeIndex)}
              >
                {menuItems.map((item, index) => (
                  <SwiperSlide key={index}>
                    <section>
                      <Image
                        src={item.image}
                        width={300}
                        height={300}
                        alt={`Producto ${index + 1}`}
                        priority={false}
                      />
                      <p>{item.name}</p>
                      <p>{item.price} $</p>
                    </section>
                  </SwiperSlide>
                ))}
              </Swiper>
            </header>
            <div className={styles.OrderControls}>
              <button onClick={() => addToOrder(menuItems[activeIndex])}>+</button>
              <span>{getCurrentItemQuantity()}</span>
              <button onClick={() => removeFromOrder(menuItems[activeIndex])}>-</button>
            </div>
          </>
        ) : (
          <p>No items added to the menu.</p>
        )}
        <Link href={"/AdminPage"}>Admin Page</Link>
        <Link href={"/SendOrder"}>sentOrder</Link>
      </main>
      
    </>
  );
};

export default Menu;